### ISSUE TITLE
MNIST Notebook is slow

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#142]
We are running a LOT of quantum circuits in the MNIST tutorial. Maybe we should find a way to trim it down a little bit ? so CI can run faster. Right now it takes as much as 30+ mins on all the notebooks.

**Comment by va9abund** [comment]
Is it possible to reproduce this tutorial on actual quantum hardware? My guess is that despite of a numerous number of, it might be caused by using simulator.

**Comment by MichaelBroughton** [comment]
It's possible that if we had a big(ger) quantum computer the differences between the quantum computer and the classical computer could get smaller and it would do better.

Glad you enjoyed the tutorial :).

We dialed back the runtime of this notebook on CI with: #155 so we can close this now.
