### ISSUE TITLE
Finish C++ Backend for SampledExpectation

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#144]
This is a deceptive amount of work. Roughly we will need to do the following things:

1. Add ability to calculate sampled expectation in `qsim` and `src`.
2. Add a new C++ op that will have the same signature as the python.
3. Link that C++ op into `get_sampled_expectation_op`.

No need to modify any other tests or layers since this should just propagate up through the API.

**Comment by MichaelBroughton** [comment]
Step 1 is done, before we move on to 2. #158 Should go in and we can start testing state_space a little more to make our lives easier for step 2.

**Comment by zaqqwerty** [comment]
Resolved by #196
