### ISSUE TITLE
Replace format_ipynb script with tf docs nbfmt

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#148]
The current `scripts/format_ipynb.py` has a slightly different convention than the tf docs nb formatter at https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py; per @lamberta, the latter is also designed to be compatible with Colab downloads

**Comment by lamberta** [comment]
(just saw you reopened)
Take a look at this CI check to install the `tensorflow-docs` package and test with `nbfmt`: https://github.com/tensorflow/docs-l10n/blob/master/.github/workflows/ci.yaml#L11

To run it:

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

$ python3 -m tensorflow_docs.tools.nbfmt notebook.ipynb
```

Recently submitted a GitHub Actions workflow to automatically add a format commit, but it needs a webhook to run the workflow with permissions: https://github.com/tensorflow/docs-l10n/blob/master/.github/workflows/bot-pr-fix.yaml
And still working out it can play nice with the CLA bot.
