### ISSUE TITLE
tensorflow_quantum/core/ops/_tfq_simulate_ops.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by htmbennis** [tensorflow/quantum#157]
I run the notebook "Hello many worlds" on google Colab
when I run : import tensorflow_quantum as tfq
I get the following error :
NotFoundError: /usr/lib/python3/dist-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: cannot open shared object file: No such file or directory
Of course, I have successfully installed tensorflow-quantum with :  !pip install tensorflow-quantum

**Comment by htmbennis** [comment]
not reproductible

**Comment by Nimitkothari** [comment]
its due to older version of tensorflow.

Do following steps:
    pip uninstall tensorflow
    pip install tensorflow

the above commands install latest version of tensorflow.
you wont face the error again.
