### ISSUE TITLE
Typo in `hello_many_worlds.ipynb` images

### ISSUE THREAD

**Issue by peterse** [tensorflow/quantum#164]
The following images have typos in the circuit they're depicting, compared to the circuits defined in the body of the tutorial.
[nn_control1.png](https://github.com/tensorflow/quantum/blob/master/docs/tutorials/images/nn_control1.png)
[nn_control2.png](https://github.com/tensorflow/quantum/blob/master/docs/tutorials/images/nn_control2.png)

It would clarify things to change all of the circuits to match up.

**Comment by MichaelBroughton** [comment]
@trevormccrt can you look into fixing these ?

**Comment by smitsanghavi** [comment]
+1, It would be nice to fix these typos. This is the first tutorial that people will look at.

Also, it would better if the images were in a more editable format so that anyone can contribute.

**Comment by zaqqwerty** [comment]
Resolved by #268
