### ISSUE TITLE
Implement engine_util.py.

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#186]
Like batch_util which is designed for fast parallel calls to Cirq simulator/Sampler objects we should make `engine_util` which is designed for careful and efficient calls to Cirq Sampler objects to ensure maximum compatibility with Cirq's engine interface. This will need to wait until we finish #185 .

**Comment by zaqqwerty** [comment]
See the discussion [here](https://github.com/tensorflow/quantum/pull/316#issuecomment-667722886)
