### ISSUE TITLE
Minor bug in Meta-Learning QAOA notebook

### ISSUE THREAD

**Issue by JPalakapilly** [tensorflow/quantum#191]
There's a line in the call function of the QRNN class that I think is incorrect. `prev_input` should be assigned `inputs[4]` instead of `inputs[3]`. Code shown below with stars around the line in question.
```
class QRNN(tf.keras.layers.Layer):
  def __init__(self, symbol_names):
    super(QRNN, self).__init__()
    self.shared = tf.keras.layers.Dense(25, name="shared")
    self.state = tf.keras.layers.Dense(25, name="state")
    self.params = tf.keras.layers.Dense(2, name="params")
    self.expectation = tfq.layers.Expectation()
    self.symbol_names = symbol_names

  def call(self, inputs):
    circuits = inputs[0]
    ops = inputs[1]
    state = inputs[2]
    params = inputs[3]
    **prev_output = inputs[3]**
    joined = tf.keras.layers.concatenate([state, params, prev_output])
    shared = self.shared(joined)
    s_inp = self.state(shared)
    p_inp = self.params(shared)
    exp_out = self.expectation(circuits,
                               symbol_names=self.symbol_names,
                               symbol_values=p_inp,
                               operators=ops)
    return [circuits, ops, s_inp, p_inp, exp_out]
```

**Comment by MichaelBroughton** [comment]
Good catch. @zaqqwerty can you take this on ?

**Comment by zaqqwerty** [comment]
I'll address this now

**Comment by JPalakapilly** [comment]
Awesome. I’ve read the paper and am trying to build on this for a project for class. Any chance y’all have code on the VQE Hubbard model that you can share with me?

**Comment by MichaelBroughton** [comment]
Unfortunately no, we don’t have any VQE Hubbard stuff laying around in TFQ. Check out here: https://github.com/quantumlib/OpenFermion and https://openfermion.readthedocs.io/en/latest/openfermion.html . You should be able to setup your circuits using OpenFermion and then just run them through TFQ.

Going to close now since the original issue is fixed now.
