### ISSUE TITLE
Google Cirq Gate Throws Serialization Error

### ISSUE THREAD

**Issue by dominicpasquali** [tensorflow/quantum#200]
While testing out TFQ's hello_many_worlds example (https://www.tensorflow.org/quantum/tutorials/hello_many_worlds), some Cirq gates throw a serialization error when passed through TFQ's convert to tensor function.

For example, while trying out the identity matrix:

![mATRIX1](https://user-images.githubusercontent.com/7927409/78954990-b218b900-7a92-11ea-8637-9fb1016c898c.png)

I get the following serialization error:

![ErrorCode](https://user-images.githubusercontent.com/7927409/78954760-f3f52f80-7a91-11ea-9a96-e22d85ac6e26.png)

**Comment by MichaelBroughton** [comment]
Yes, if you look at `tfq.util.get_supported_gates` it will give you a list (might actually be a dict) of all of the gates supported in TFQ. TFQ Curently doesn't support `cirq.I` or `cirq.MatrixGate` (They don't play nice with Cirq's proto serialization yet).

To give a little more context:

1. We wanted to be able to serialize and deserialize circuits to protocol buffer representations when passing them between our ops (C++ protocol serialization and deserialization are very fast).

2. Cirq provides protocol buffer serialization code that supports many (but not all) of it's gates. We have supported all that we can in the current Cirq version (0.7.0) and as Cirq releases continue to happen we will likely be able to add more.

Does that help clear things up ?

**Comment by dominicpasquali** [comment]
Yes, that absolutely clears things up, thank you! I totally missed the documentation for  `tfq.util.get_supported_gates`. Also thank you for giving me an idea of what the backend is doing.
