### ISSUE TITLE
MPS Integration

### ISSUE THREAD

**Issue by zphy** [tensorflow/quantum#208]
Are there plans for integration of MPS/DMRG simulation capabilities, either in TFQ or Cirq? Seems like a useful thing to have to access larger system sizes for some simple models for now

**Comment by QuantumVerd** [comment]
Yes, there is something in the works along these lines.

**Comment by MichaelBroughton** [comment]
The timeline for adding MPS or other kinds of simulators is likely going to be a long one for both TFQ and Cirq. #210 Goes over some methods that could serve as a somewhat "hacky" workaround to implement things like sampling or expectation calculation using alternative backends (although the methods in #210 have never been tested for such things).

If there is any outside interest in implementing new simulators it might make more sense to open an issue on TFQ or Cirq with a design proposal for how to incorporate them.

Going to close for now.
