### ISSUE TITLE
Installation instructions not totally compatible with Python 3.8

### ISSUE THREAD

**Issue by jarrodmcc** [tensorflow/quantum#213]
The instructions (those related to using pip install) are specific to versions of tensorflow etc that are natively accessible from pip due to the way they are tagged in Python 3.7 but not Python 3.8.  One could either update the instructions or mention that it is specific to 3.7 and below to avoid installation confusion.

**Comment by MichaelBroughton** [comment]
Ahhh very good point. We could be more clear in specifying which python3 versions we support. We went for all possible python version compatible with https://pypi.org/project/tensorflow/#files and https://cirq.readthedocs.io/en/stable/install.html. Which is 3.6 and 3.7. Fix is here #214
