### ISSUE TITLE
[Discuss] Windows build failed due to uint64_t

### ISSUE THREAD

**Issue by jaeyoo** [tensorflow/quantum#217]
We recently got the compilation error [C2398](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2397?view=vs-2019) (interestingly, it `is` C2398, not C2397, as listed [here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-errors-c2300-through-c2399?view=vs-2019)) during nightly build on Windows platform.
```
\\local_config_tf\include\unsupported\Eigen\CXX11\src/Tensor/TensorMap.h(267): error C2398: Element '3': conversion from 'uint64_t' to 'ptrdiff_t' requires a narrowing conversion
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc(106): note: see reference to function template instantiation 'std::complex<float> &Eigen::TensorMap<Eigen::Tensor<T,3,1,IndexType>,16,Eigen::MakePointer>::operator ()<uint64_t>(__int64,__int64,uint64_t)' being compiled
        with
        [
            T=std::complex<float>,
            IndexType=Eigen::DenseIndex
        ]
```

The ln 106 in tfq_calculate_unitary_op.cc is [this](https://github.com/tensorflow/quantum/blob/master/tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc#L106).
```cc
tensorflow::Tensor *output = nullptr;
...
auto output_tensor = output->tensor<std::complex<float>, 3>();
...
for (uint64_t j = 0; j < state_size; j++) {
  for (uint64_t k = 0; k < state_size; k++) {
    output_tensor(i, j, k) = state->GetEntry(j, k);
  }
}
```
The remedy in MSDN docs is specifying the type casting, e.g. `static_cast<ptrdiff_t>(j)` and  `static_cast<ptrdiff_t>(k)` in my understanding.  In addition, when I looked up the definition of tensorflow::Tensor::tensor(), I found out:
```cc
template <typename T, size_t NDIMS>
typename TTypes<T, NDIMS>::Tensor tensor();
```
I am curious about if `static_cast<size_t>()` is also possible or not. However, we really want to take 64-bit address due to the big size of tensors, but the fact that `size_t` can be 32-bit, dependent of platforms, and I am worrying if it is intended behavior or not.

I hope to hear your ideas. Thanks!

**Comment by MichaelBroughton** [comment]
Ahhh I saw the build failure. I had come to the same conclusion but opted to use `size_t` I'm not as worried about 64 bit indexing for unitary matrix for the following reason:

A unitary has memory footprint `2^2n * 64 bits`, indexing into `output_tensor` using a `size_t` will work up to 31 qubits meaning we'd need to have allocated `35 Exabytes` before we hit an overflow error. So I think narrowing down to `size_t` or `ptrdiff_t` is safe in this case. 

With state it wouldn't be because `2^n * 64 bits` with 33 qubits is still in the gigabtyes range so in state we do need `uint64_t`. I just opened #218 for your approval :)

**Comment by jaeyoo** [comment]
Oops,

**Comment by MichaelBroughton** [comment]
Oops guess windows is still picky about the difference between `size_t` and `ptrdiff_t` haha.

**Comment by jaeyoo** [comment]
Saw windows compiler were satisfied with our remedy :) @MichaelBroughton  Thank you for your help!
https://pypi.org/project/tfq-nightly/0.3.0.dev20200424/#files
