### ISSUE TITLE
Allow ragged operators?

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#224]
Currently the length of all operator lists must be equal.  Would be nice to figure out a way to make the following work:
```
q0, q1 = cirq.GridQubit.rect(1,2)
z0 = cirq.Z(q0)
z1 = cirq.Z(q1)
p_tensor = tfq.convert_to_tensor([[z0], [z0, z1]])
c0 = cirq.Circuit([cirq.X(q0)])
c0c1 = cirq.Circuit([cirq.X(q0), cirq.X(q1)])
c_tensor = tfq.convert_to_tensor([c0, c0c1])
tfq.layers.Expectation()(c_tensor, operators=p_tensor)
```

**Comment by MichaelBroughton** [comment]
I think @peterse had talked about this a while ago too. One concern I have with doing this is that we only really want to use Ragged when we have to and I don't think we should use ragged just out of a need for more convenience. If a user wants to have different sizes of paulis they can add a 0*PauliI term or they could split up the circuits into the ones they want to take ZZ on and the ones they want to take XX on and then just run those through different instances of the op. Odds are if the user knows ahead of time they are using certain numbers of ops with certain circuits they could pair them up and send them through different ops.

**Comment by zaqqwerty** [comment]
Sounds good, seems like we won't be pursuing this.
