### ISSUE TITLE
Upgrade to cirq 0.8

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#228]
Cirq 0.8 is out. Lets see if we can upgrade to depending on it.

**Comment by XiaoTailong** [comment]
It seems that TFQ 0.2 is not suitable for Cirq 0.8. I expect the new version of TFQ.

**Comment by MichaelBroughton** [comment]
Yes. TFQ 0.2 does NOT work with cirq 0.8. We also made the mistake of accidentally doing `cirq >=0.7.0` in our `setup.py` file for 0.2. This will be changed when the next TFQ comes out and pin us to a particular version so a user doesn't accidentally install cirq 0.8 and have tfq error out when using it.
