### ISSUE TITLE
_tfq_utility_ops.so not found

### ISSUE THREAD

**Issue by cubicgate** [tensorflow/quantum#242]
When I ran the example: hello_many_worlds.py, I got this error:

lib\site-packages\tensorflow_quantum\core\ops\tfq_utility_ops.py", line 19, in <module>
    UTILITY_OP_MODULE = load_module("_tfq_utility_ops.so")

tensorflow_quantum\core\ops\_tfq_utility_ops.so not found

I am using tensorflow  2.1.0 on Windows 10

**Comment by MichaelBroughton** [comment]
Would you mind giving a little more information ?

Could you post the version of TFQ you are using and whether or not this was run locally or in the cloud along with the full error output ?

**Comment by jaeyoo** [comment]
If the error message is correct, I guess somewhere the code was broken concatenating two paths "tensorflow_quantum\core\ops" and "_tfq_utility_ops.so". It missed "\" between them.

**Comment by cubicgate** [comment]
> Would you mind giving a little more information ?
> 
> Could you post the version of TFQ you are using and whether or not this was run locally or in the cloud along with the full error output ?

I have tried different versions of cpu and gpu so I am sorry that I can not reproduce the whole error message now.  Thanks for your kindness to help me!

**Comment by cubicgate** [comment]
> If the error message is correct, I guess somewhere the code was broken concatenating two paths "tensorflow_quantum\core\ops" and "_tfq_utility_ops.so". It missed "" between them.

I did see the issue of the two paths as you suggested, but after I made the correction, I still had the same error message.  Thanks for your help!

**Comment by cubicgate** [comment]
Hi @MichaelBroughton , I tried different ways and still did not know what was the reason for my issues. Finally, I tried using anaconda, it works now.  Thanks!
