### ISSUE TITLE
Example for image segmentation

### ISSUE THREAD

**Issue by armaneshaghi** [tensorflow/quantum#248]
Does anyone know of an example code of TF Q for image segmentation? Would such an application be even possible?

**Comment by MichaelBroughton** [comment]
This might be a question best suited for some sort of stackoverflow subsite where people are able to weigh in on different answers. I would recommend you check out: https://quantumcomputing.stackexchange.com/questions/11533/how-mature-is-the-tensorflow-quantum-library . It gives a rough overview of the kinds of ways ML and QC fit together. 

To answer your first question: I personally don't know of any image segmentation demos using TFQ. 

I'll try my best to answer your second question from two different standpoints.

1st Standpoint: **Engineer looking to improve Image segmentation pipeline**: Right now we don't know any ways that quantum computing can improve image segmentation and like @dabacon says in his stackoverflow answer `None of this (quantum computing + machine learning) is at a stage where it is at all considered something that should be mentioned in the same sentence with "production".`. So, yes it is possible, but won't be practical. 

2nd Standpoint: **Researcher looking to explore the idea of image segmentation using hybrid models**: Yes it is possible. You might find some interesting results or new ways of thinking about hybrid models. Although image segmentation is a pretty unconventional application of hybrid models. Classical models are already really great at Image segmentation and there might be other areas where hybrid models would have more of an edge over the purely classical models (perhaps scenarios where the data is harder for the classical computer to store/represent). 

In general TFQ is targeted more towards the research audience.

Does that answer your question ?
