### ISSUE TITLE
Error in tfq.layers.Sample()

### ISSUE THREAD

**Issue by cubicgate** [tensorflow/quantum#254]
When I tried the example: https://www.tensorflow.org/quantum/api_docs/python/tfq/layers/Sample
sample_layer = tfq.layers.Sample()
output = sample_layer(get_circuit(), repetitions=4)
output
I got:
<tf.RaggedTensor [[[0, 0], [0, 0], [0, 0], [0, 0]]]>
Instead of [1,1] as shown in the example.
Here is the full message:

tensorflow_core\python\util\deprecation.py:507: calling count_nonzero (from tensorflow.python.ops.math_ops) with axis is deprecated and will be removed in a future version.
Instructions for updating:
reduction_indices is deprecated, use axis instead
<tf.RaggedTensor [[[0, 0], [0, 0], [0, 0], [0, 0]]]>

**Comment by MichaelBroughton** [comment]
Could you please share the exact code you used to generate this output ?

**Comment by cubicgate** [comment]
Hi @MichaelBroughton : Here it is:
import tensorflow as tf
import tensorflow_quantum as tfq
import cirq

def get_circuit():
    q0 = cirq.GridQubit(0, 0)
    q1 = cirq.GridQubit(1, 0)
    circuit = cirq.Circuit(
        cirq.X(q0),
        cirq.CNOT(q0,q1)
    )

    return circuit
 
sample_layer = tfq.layers.Sample()
output = sample_layer(get_circuit(), repetitions=4)
print(output)

**Comment by MichaelBroughton** [comment]
I was not able to reproduce your all zero output. What version of TFQ are you using ?

**Comment by cubicgate** [comment]
I use: 0.3.0

**Comment by zaqqwerty** [comment]
Seeing that your error message is coming from `tensorflow_core`, I wonder what version of TF do you have installed?  TFQ currently requires `tensorflow==2.1.0`.

**Comment by MichaelBroughton** [comment]
Going to close since this has gone stale.
