### ISSUE TITLE
Add Supported for PhasedXZGate

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#257]
There's a new and obscure gate in Cirq! The PhasedXZGate. We should add support for this gate inside of TensorFlow Quantum. Like all gates this means:

1. Adding rules to `serializer.py`
2. Implementing the gate in qsim
3. Adding a rule in `tfq_ps_decompose_op.cc`
4. Hooking the gate into all existing python fuzz tests and `supported_gates` function in `util.py`.

Do @jaeyoo or @zaqqwerty have any interest in taking this on ?

**Comment by jaeyoo** [comment]
I am interested in 1 & 3.

**Comment by MichaelBroughton** [comment]
Sounds good :)

**Comment by jaeyoo** [comment]
Thanks. Let me open a PR for 1 in this week

**Comment by MichaelBroughton** [comment]
After talking with the people working on qsim it looks like this may be looked after for us already. This should come for free when we switch over to using the OSS version of qsim

**Comment by jaeyoo** [comment]
Thanks a lot, then I will not work on it :)

**Comment by MichaelBroughton** [comment]
This gate is in now.
