### ISSUE TITLE
TFQ with Sympy v 1.5 compatibility

### ISSUE THREAD

**Issue by edgard-pierre** [tensorflow/quantum#259]
Hi.
Reading the requirement.txt file, I noticed there were a strict requirement on Sympy version: sympy==1.4 . Since 1.5 was release with a lot of new features, I was wondering if a tfq version compatible with sympy 1.5 (or more) was planned. 
Thanks.

**Comment by MichaelBroughton** [comment]
Yes! Supporting updates to newer sympy versions should be doable. I believe it would ultimately come down to tinkering with the tests and logic in `serializer_test.py`.

Would anyone be interested in taking this on ? @zaqqwerty or @jaeyoo or @edgard-pierre
