### ISSUE TITLE
Is there a way to directly feed quantum states into PQC layer?

### ISSUE THREAD

**Issue by refraction-ray** [tensorflow/quantum#260]
It seems to me the quantum data as input layer are always via ``convert_to_tensor`` from ``cirq.Circuit``.  In some scenarios, we may need to feed the circuit model complicated input states which are not easily captured or built by a circuit on zero states (though this can always can be done in theory, the depth of the preparation circuit may be very large or the explicit construction is hard to find). 
For example, one may want to use PQC to evaluate some quantum ground states from given Hamiltonians (which can be obtained by exact diagnoalization in numerical simulations), such ground states may be not easy to encode as a circuit from zero states.

**Comment by vinitX** [comment]
#210 Contains a similar issue.

**Comment by refraction-ray** [comment]
@vinitX , thanks for pointing this, I will have a look on it and close this issue
