### ISSUE TITLE
qsim path is weird

### ISSUE THREAD

**Issue by jaeyoo** [tensorflow/quantum#272]
Let's investigate why this happens:
```cc
#include "../qsim/..."
```
and if it is possible that:
```cc
#include "qsim/..."
```

**Comment by MichaelBroughton** [comment]
I think this has to do with: https://github.com/quantumlib/qsim/issues/69

**Comment by jaeyoo** [comment]
I figured out what's going on the weird path. In bazel, it's creating the temporary cache directory path `bazel_{project_name}`. For example, for tensorflow quantum, it has `quantum` as project name, so it creates `bazel_quantum` directory. Inside it, it collects the whole dependency library path as well as `tensorflow_quantum` itself. So, in the directory, we can observe:

- `tensorflow_quantum`
- `qsim`

so to access the `qsim` directory, we need to use `../` as prefix.

To make the `qsim` itself as default include path, like `#include "qsim/"`, we can use the bazel's `cc_library(includes = ["PATH"])` option. To do that, we may re-organize `qsim` directory structure. For example, add `qsim` directory, and put `lib` directory under it, then we can use `#include "qsim/lib/..."`.

Let me prepare a PR to fix this, and maybe this will be a starter for migrating qsim to full bazel supports as mentioned in https://github.com/quantumlib/qsim/issues/69

**Comment by mhucka** [comment]
It looks like this was taken care of. Closing this issue, but please feel free to reopen the issue if that's in error.
