### ISSUE TITLE
Some links broken in documentation

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#287]
The links to the possible `cirq` backends in the tfq.layers documentation yield a 404 error, for example see documentation for the [Sample layer](https://www.tensorflow.org/quantum/api_docs/python/tfq/layers/Sample).

**Comment by MichaelBroughton** [comment]
This is a known issue. Pretty sure it has to do with @yashk2810 working with other docs ?

**Comment by yashk2810** [comment]
This should have been fixed last week but my jobs failed due to a TFP issue.

It'll get fixed today or tomorrow.

**Comment by MichaelBroughton** [comment]
Fixed.
