### ISSUE TITLE
Add python 3.8 Support

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#290]
Python 3.8 is out now and we might want to look into making wheel files internally for our next major release. It might also make sense to revive the old tf 2.2 upgrade PR #181 and convert it to a 2.3 upgrade, since tf 2.1.0 is no longer supported on python 3.8. What do you think @jaeyoo ?

In order to tackle this we would need to:
1. Upgrade our dependency from tf 2.1.0 to 2.2.0 or wait for 2.3.0
2. Add a new internal build for nightly and release builds on Py 3.8

**Comment by jaeyoo** [comment]
For 1, now TF is 2.3.0-rc1 and the 2.3.0 release will come out soon. Let's wait for it.

For 2, yes, we need to add internal build for nightly and release. Let's do it after 1?

**Comment by MichaelBroughton** [comment]
Ok yes, we do have to do 2 after 1 since tf 2.1.0 isn’t available for python 3.8. Would you be interested in taking this on in a week or two ?

**Comment by jaeyoo** [comment]
Please let me take 1 & 2. after July 29. I am busy until July 28. Thanks.

**Comment by theRoughCode** [comment]
Any plans for TF 2.3.0 support? I need `tensor_scatter_nd_max` (https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_max) available then.

**Comment by MichaelBroughton** [comment]
We are hoping to get upgraded to 2.3 in the nightly within a week or two.

**Comment by MichaelBroughton** [comment]
@theRoughCode Nightly builds should now depend on tf 2.3.0 (On Mac and Linux at least. The windows is upgrade is being...... difficult).

**Comment by theRoughCode** [comment]
Thanks for the update @MichaelBroughton! I'm using Google Colab, so I don't think Windows will be a problem! :)

**Comment by MichaelBroughton** [comment]
Closing now since we have 3.8 on nightly and support will be in the next release.
