### ISSUE TITLE
Official docker container?

### ISSUE THREAD

**Issue by we-taper** [tensorflow/quantum#305]
A simple image based on Tensorflow's would be cool.

For example:

```Dockerfile
FROM tensorflow/tensorflow:2.1.0-py3

RUN python -m pip install tensorflow-quantum==0.3.0
```

**Comment by MichaelBroughton** [comment]
Interesting idea, It doesn't look like other TF addons like probability are using their own docker containers. @MarkDaoust or @yashk2810 what are your thoughts on this ?

**Comment by yashk2810** [comment]
Depends on how important it is. Why is a docker container needed though?

Note: Creating docker containers comes with a maintenance cost. So I would recommend going through all the positives and negatives of it and then deciding on what to do 😅

**Comment by we-taper** [comment]
Cool, it makes sense to save maintenance cost here. I don't think there is too much extra effort to create Docker file based on TensorFlow's.
