### ISSUE TITLE
Sporadic CI errors

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#324]
Installing the requirement `tensorflow==2.1.0` sometimes fails with the error `THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE`, for example see the actions [here](https://github.com/tensorflow/quantum/runs/933060863?check_suite_focus=true) and [here](https://github.com/tensorflow/quantum/runs/923682631?check_suite_focus=true)

**Comment by jaeyoo** [comment]
https://github.com/tensorflow/tensorflow/issues/27794#issuecomment-666730336

As explained above, it seems not TF issue...

**Comment by MichaelBroughton** [comment]
Hmmm seems like this could be a networking issue ?

Let's keep an eye on things and if it gets unbearable perhaps as a quick fix, we can drop the hash check on the downloads.

**Comment by mkaze** [comment]
See [this](https://github.com/actions/virtual-environments/issues/1354). It seems it's an underlying issue of Github Actions.

**Comment by zaqqwerty** [comment]
The issue [seems to be resolved](https://github.com/actions/virtual-environments/issues/1354).
