### ISSUE TITLE
Does tensorflow quantum add support for simulation on  single or multiple GPUs?

### ISSUE THREAD

**Issue by amandalqy** [tensorflow/quantum#341]
Ｏnce I thought tensorflow quantum didn't  not support simulation on single or multiple GPUs. But recently I saw xabomon  said ＂we are trying to set up  tensorflow quantum to run in our small GPU cluster (featuring two nvidia Tesla P100 16GB). ＂in the "Installing TFQ in a GPU cluster " issue. So does tensorflow quantum add support for simulation on  single or multiple GPUs now?

**Comment by amandalqy** [comment]
![tensor](https://user-images.githubusercontent.com/44419296/90112159-37361680-dd82-11ea-8725-40d279a33420.png)

**Comment by MichaelBroughton** [comment]
We still do not support quantum circuit simulation on GPU or TPU devices. I was under the impression that xabomon was going to use the GPU for strictly vanilla tensorflow things (which would still work with GPUs), sorry for the confusion.
