### ISSUE TITLE
Builds failing on calls to data store

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#344]
Error message:
```Exception: URL fetch failure on https://storage.googleapis.com/download.tensorflow.org/data/quantum/spin_systems/TFI_chain.zip : 403 -- Forbidden```

**Comment by MichaelBroughton** [comment]
Should be fixed now. Just confirmed with: `wget https://storage.googleapis.com/download.tensorflow.org/data/quantum/spin_systems/TFI_chain.zip`
