### ISSUE TITLE
View source on github link on TF API documentation page results in 404

### ISSUE THREAD

**Issue by jacksonwb** [tensorflow/quantum#414]
All 'View source on github' links on the official api documentation pages have a bad link.

On the following page:
https://www.tensorflow.org/quantum/api_docs/python/tfq

Button links to:
https://github.com/tensorflow/quantum/blob/v0.4.0/tensorflow_quantum/__init__.py

**Comment by jacksonwb** [comment]
@zaqqwerty

**Comment by MichaelBroughton** [comment]
Could you check to see that the problem is fixed now ? (We had mislabeled some of the releases)

**Comment by jacksonwb** [comment]
Fixed! Thanks.
