### ISSUE TITLE
serializer.py should use sympy.core.mul.Mul instead of sympy.mul.Mul

### ISSUE THREAD

**Issue by jaeyoo** [tensorflow/quantum#423]
This recent PR in sympy moved `sympy.add` and `sympy.mul` under `sympy.core`

https://github.com/sympy/sympy/commit/98fb163988b5ad8b72647b682efebd92c8f895c3

**Comment by jaeyoo** [comment]
`sympy.numbers` -> `sympy.core.numbers`

**Comment by MichaelBroughton** [comment]
We are currently pinned to sympy==1.5. When we do an upgrade to the latest version this will be good to know when things break :)
