### ISSUE TITLE
Use tf.convert_to_tensor for symbol_values in differentiator docstrings

### ISSUE THREAD

**Issue by therooler** [tensorflow/quantum#427]
**Python: 3.8
TFQ: 0.4.0**

I was trying to see what kind of speed up I would get from using `tfq.differentiators.Adjoint`. The [docstring example](https://www.tensorflow.org/quantum/api_docs/python/tfq/differentiators/Adjoint) runs fine, but when I add more parameters to the circuit, I get the following error message
```python
Traceback (most recent call last):
  File "/home/rooler/Documents/tfq/kagome/does_adjoint_work.py", line 27, in <module>
    grads = g.gradient(expectations, symbol_values_tensor)
  File "/home/rooler/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1067, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/home/rooler/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/home/rooler/anaconda3/envs/tfq/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py", line 450, in actual_grad_fn
    raise ValueError(
ValueError: ('custom_gradient function expected to return', 5, 'gradients but returned', 4, 'instead.')
```
Code to reproduce:
```python
import cirq
import tensorflow_quantum as tfq
import tensorflow as tf
import sympy
import numpy as np

my_op = tfq.get_expectation_op()
adjoint_differentiator = tfq.differentiators.Adjoint()
# Get an expectation op, with this differentiator attached.
op = adjoint_differentiator.generate_differentiable_op(
    analytic_op=my_op
)
qubit = cirq.GridQubit(0, 0)
circ = cirq.Circuit(cirq.X(qubit) ** sympy.Symbol('alpha'))
circ.append(cirq.Y(qubit) ** sympy.Symbol('beta'))
circuit = tfq.convert_to_tensor([circ])

psums = tfq.convert_to_tensor([[cirq.Z(qubit)]])
symbol_values_array = np.array([[0.123, 0.3]], dtype=np.float32)

# Calculate tfq gradient.
symbol_values_tensor = tf.convert_to_tensor(symbol_values_array)
with tf.GradientTape() as g:
    g.watch(symbol_values_tensor)
    expectations = op(circuit, ['alpha', 'beta'], symbol_values_tensor, psums
)
grads = g.gradient(expectations, symbol_values_tensor)
print(grads)
```

I am having some trouble trying to debug this. Any suggestions?

**Comment by zaqqwerty** [comment]
I reproduced this error with this code in colab.  I find that if I replace `['alpha', 'beta']` with `tf.constant(['alpha', 'beta'])`, the error goes away.  However I find that the original code snippet in the Adjoint Diff docstring does not have this same error.  We should get to the bottom of this, but for now making sure all op inputs are tensors seems to fix it

**Comment by MichaelBroughton** [comment]
This was actually an undocumented backwards breaking change in regular TensorFlow ( I spoke with an engineer about this when we first upgraded from 2.1.0 to 2.3.1.). Normally it would be fine to pass a python list of strings in, but since the change we should recommend/encourage users to pass in constant tensors. You can see in here when we did the upgrade that we also needed this change internally as well: https://github.com/tensorflow/quantum/pull/340/files . 

Let's convert this issue into: Differentiator docstrings do not convert to tensor for symbol_values.

**Comment by therooler** [comment]
Changing to tf.constant did the trick. Thanks.
