### ISSUE TITLE
Graph Network example

### ISSUE THREAD

**Issue by rdisipio** [tensorflow/quantum#435]
Hi,

   it would be nice if you could add a notebook tutorial concerning graph networks. I'm thinking specifically about the quantum graph convolutional neural networks discussed in the paper [arXiv:1909.12264](https://arxiv.org/pdf/1909.12264.pdf), but anything simple enough to get started would be enough.

Cheers,
Riccardo

**Comment by MichaelBroughton** [comment]
Hi @rdisipio ,

A minimal working example can already be found here (linked from both the TensorFlow Quantum arxiv paper and TensorFlow Quantum website): https://github.com/tensorflow/quantum/blob/research/qgrnn_ising/qgrnn_ising.ipynb . I will say that we don't pay as close attention to the `research` branch, so feel free to give it a try and if anything breaks we can address the breakage in this issue.

-Michael

**Comment by MichaelBroughton** [comment]
Any updates on this ?
