### ISSUE TITLE
Capturing measurement results from repetitions in PQC or C-PQC layer

### ISSUE THREAD

**Issue by hblxuor** [tensorflow/quantum#439]
I'm using TFQ to run QAOA simulations, mainly using the ControlledPQC layer to feed keras layer outputs to the QAOA circuit and training the whole thing. I'm using repetitions in ControlledPQC to get averaged outputs.  I'd like to monitor the individual measurement results in the repetition, in order to terminate the loop if any of the measured states is the solution state. I see that tf.Sample returns every measurement result, for example.  Is it possible to get the measurement results from ControlledPQC or the other layers that use repetitions?

**Comment by MichaelBroughton** [comment]
Hi @hblxuor good question!

`ControlledPQC` is designed to be a more high level layer and as such won't provide access to the samples used. If you would like to examine samples from a circuit while simultaneously optimizing the circuit you will have to move away from these higher level layers to the `tfq.layers.SampledExpectation` and `tfq.layers.Sample`. In particular you will likely need to have one `tfq.layers.SampledExpectation` attached to your input circuit tensor and one `tfq.layers.Sample` attached to your input circuit tensor as well. These layers would need to share the same learnable variables. Then in between training steps that backprop through the `SampledExpectationLayer` you could examine the individual bit strings by looking at the outputs from the `tfq.layers.Sample` layer. Does this help clear things up ?

**Comment by hblxuor** [comment]
It does- thank you!
