### ISSUE TITLE
AttributeError: module 'tensorflow_quantum' has no attribute 'resolve_parameters'

### ISSUE THREAD

**Issue by Raghvender1205** [tensorflow/quantum#440]
I was following up with the Quantum Data notebook on Tensorflow Quantum.
During 
def prepare_pqk_circuits(qubits, classical_source, n_trotter=10):
in the last i returned
 return tfq.resolve_parameters(
      full_circuits, tf.convert_to_tensor([str(x) for x in symbols]),
      tf.convert_to_tensor(classical_source*(n_qubits/3)/n_trotter))
but when testing and preparing data encoding around the dataset it gave me this error
and its very slow to execute

https://www.tensorflow.org/quantum/tutorials/quantum_data

**Comment by Raghvender1205** [comment]
Anyone who would like to help me on this.

**Comment by MichaelBroughton** [comment]
Hi @Raghvender1205 . I wasn't able to reproduce this issue in cloud. I ran the tutorial by clicking on the "Run in Google Colab" button here https://www.tensorflow.org/quantum/tutorials/quantum_data and it ran all the way through just fine. If you are running on your local machine, could you first make sure you are running TensorFlow 2.3.1 as well as TensorFlow Quantum 0.4.0 to see if that fixes things ? If the error persists could you please provide more details on what OS, version of python as well as a more detailed error log etc. ?

**Comment by Raghvender1205** [comment]
Ok

**Comment by MichaelBroughton** [comment]
Any updates on this ?

**Comment by Raghvender1205** [comment]
I am not able to execute the code on jupyter due to 
Lib\site-packages\tensorflow_quantum\core\ops\_tfq_simulate_ops.so not found
error, but it showed no error with Google Cloud

**Comment by MichaelBroughton** [comment]
This is still not enough information to begin to try and diagnose the problem. Can you take a look at issues like this one: #407 and include the full output logs, what particular section caused the error as well as what OS + versions of python, tfq etc. you are working with.

**Comment by Raghvender1205** [comment]
Sure, I will do that.

**Comment by MichaelBroughton** [comment]
Any updates on this ?
