### ISSUE TITLE
Hello Many Worlds z0

### ISSUE THREAD

**Issue by gatorwatt** [tensorflow/quantum#467]
This is a small thing and not positive it is in error, I was a little confused in hello many worlds tutorial seeing the z0 cirq object in the check_error(.) function definition, partly because it was defined in part 1 of the notebook and everything else in part 2 appeared to be defined from scratch. So yeah just thought would share.

**Comment by MichaelBroughton** [comment]
Hi @gatorwatt thanks for posting. Looking over the tutorial it seems that redefinition of z0 might have been intentional. Do you have any suggestions on how we ought to change things to make it better ?

**Comment by gatorwatt** [comment]
Sorry am sure this is very trivial, I think my confusion stemmed from expectation that since q0 was part of the z0 definition that z0 must be tied to the original circuit from part 1. I'm interpreting your response to be indication that I misinterpreted and that z0 can be re-applied as measurement basis for other state vectors passed through expectation_from_state_vector, which at least was informative to me so thanks. 

If there was a potential improvement could perhaps just be a small clarification made between the cells for z0 definition and z0x1 definition in part 1 that this same measurement basis can be applied to other circuits passed through expectation_from_state_vector. I don't think is a big deal though.

**Comment by gatorwatt** [comment]
(Or a simpler improvement could be to just redefine z0 or something equivalent in part 2 using the qubit from the circuit in part 2 instead of q0 for clarity.)

**Comment by MichaelBroughton** [comment]
Got a fix open here #471 .
