### ISSUE TITLE
Fix warnings of c++ compilation

### ISSUE THREAD

**Issue by jaeyoo** [tensorflow/quantum#475]
There are several common warning messages of c++ compilation

1. unused variables

In this case, let's use `std::ignore`. For example, we can use:

```
std::ignore = some_function_return_value_is_not_used();
```

2. signed comparison

Let's define the type of iteration variable in the for-loop specifically. For example,

```
for (std::vector<qsim::GateFused<QsimGate>>::size_type i = 0; i < gate_fused.size() ; i++) {
// gate_fused is the type of std::vector<qsim::GateFused<qsimGate>>
```

**Comment by mhucka** [comment]
In the interest of prioritizing work on TensorFlow Quantum, I will close this issue as something that's been addressed. Please reopen this issue if that's incorrect.
