### ISSUE TITLE
small improvement to quantum data tutorial

### ISSUE THREAD

**Issue by gatorwatt** [tensorflow/quantum#479]
#In quantum data tutorial
#Under philosophy that less code is better code, in opening MNIST loading 
#could strike use of np.newaxis
#replace this line
#x_train, x_test = x_train[..., np.newaxis]/255.0, x_test[..., np.newaxis]/255.0
#with
#x_train, x_test = x_train[...]/255.0, x_test[...]/255.0
#and just replace  plt.imshow(x_train[0, :, :, 0])
#with plt.imshow(x_train[0, :, :])
#(the tf.reshape returns same form in both configurations)

#Further down a typo Choose misspelled as Chooe

**Comment by MichaelBroughton** [comment]
Thanks for raising the issue. Would you be interested in opening a PR with a fix ?

**Comment by gatorwatt** [comment]
Sure happy to. Will be my first PR on someone else’s library. To follow.
