### ISSUE TITLE
[building TF from source] C++ compilation of rule '@upb//:upb' failed

### ISSUE THREAD

**Issue by balopat** [tensorflow/quantum#482]
This is not _strictly_ TFQ related, however I've been following the https://www.tensorflow.org/quantum/install#4_build_tensorflow_from_source guide which worked for me a couple of months ago but started failing now. If possible to change something in the guide after resolving this issue, it might help others too. 

Running the bazel build command fails: 

```
ERROR: /usr/local/google/home/balintp/.cache/bazel/_bazel_balintp/cab94ab0d60fdb2915e18adf27c4c337/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
In file included from /usr/include/string.h:495,
                 from external/upb/upb/upb.h:16,
                 from external/upb/upb/upb.c:2:
In function 'strncpy',
    inlined from 'upb_status_seterrmsg' at external/upb/upb/upb.c:40:3:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: '__builtin_strncpy' specified bound 127 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Target //tensorflow/tools/pip_package:build_pip_package failed to build

```

A bit of research shows that this was an issue in micro-pb:  https://github.com/protocolbuffers/upb/issues/262.
I'm confused about the timeline as I could swear I ran through this guide in July, this issue seems older than that - but somehow popped up for me now.
I'm happy to dig deeper and find a solution / patch and share it - but if someone ran into this, I'd welcome a hint!

**Comment by MichaelBroughton** [comment]
The fact that you are building from cache with
```
/usr/local/google/home/balintp/.cache/bazel/_bazel_balintp/cab94ab0d60fdb2915e18adf27c4c337/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
```
in bazel paired and you mentioning that you had a good build a few months ago leads me to think you might have old incompatible things in there. Does doing

```
bazel clean --expunge
```
And rebuilding solve the issue ?

**Comment by zaqqwerty** [comment]
This was the same issue I was getting until the change to supporting TF 2.4.1, I think we should update the source build section for that already as in https://github.com/tensorflow/quantum/pull/473 , and only wait to change the package build sections

**Comment by balopat** [comment]
> The fact that you are building from cache with
> 
> ```
> /usr/local/google/home/balintp/.cache/bazel/_bazel_balintp/cab94ab0d60fdb2915e18adf27c4c337/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
> ```
> 
> in bazel and you mentioning that you had a good build a few months ago leads me to think you might have old incompatible things in there. Does doing
> 
> ```
> bazel clean --expunge
> ```
> 
> And rebuilding solve the issue ?

No, it doesn't, expunge, `rm -rf ~/.cache/bazel`, reinstalling dependencies, `export GCC=gcc-9`, none of that helped. Compiling 2.4.1 like in #473 does run through though!

**Comment by balopat** [comment]
Correction (duh, it's `CC`, not `GCC`) - `GCC=gcc-9` works! So, if someone wants to compile TF 2.3.1 they'll have to use GCC 9.

**Comment by MichaelBroughton** [comment]
Good catch, on further investigation the underlying issues is this: https://github.com/tensorflow/tensorflow/issues/39467 . In our install instructions we do link out to the TF source install guide which lists gcc-7 as the supported compiler and is the compiler we use when rolling our releases and nightly builds. So users should probably try and hop onto gcc-7 based on the information in the instructions. Going to close for now.
