### ISSUE TITLE
Expectation layer won't work with remote simulators

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#490]
Currently, the `Expectation` layer requires a `cirq.SimulatesFinalState`, see [this line](https://github.com/tensorflow/quantum/blob/52ccd823a7062f318304e5964b55ae521038b3f7/tensorflow_quantum/core/ops/circuit_execution_ops.py#L125).  Instead, it should be updated to directly call the methods in the new Cirq class [`cirq.SimulatesExpectationValues`](https://github.com/quantumlib/Cirq/blob/8cf782554adbafed724987de3067de7ca565fa0c/cirq/sim/simulator.py#L202).

**Comment by MichaelBroughton** [comment]
Do you have any more information on the errors they are seeing or an example that reproduces things ?
