### ISSUE TITLE
how can I use tensorflow-quantum in MAC m1

### ISSUE THREAD

**Issue by Yueh-H** [tensorflow/quantum#492]
tensorflow  can use miniconda install on  M1 
tensorflow-quantum install on Mac M1?
can anyone help me ?
thanks~

**Comment by MichaelBroughton** [comment]
Hi @Yueh-H we TensorFlow doesn't officially support anaconda builds. See #407 . 
I would recommend that you try following the standard pip install steps found on the tensorflow and tensorflow quantum website. https://www.tensorflow.org/quantum/install

**Comment by AlveeeRahman** [comment]
the ways from the website shows this error in a M1 mac, miniforge3, apple metal configurations.
![Screenshot 2022-10-25 at 12 04 32 AM](https://user-images.githubusercontent.com/108018107/197687092-3c19ea7a-d70c-4b95-a39c-b4ef6a40d948.png)
