### ISSUE TITLE
Remove parallelization logic from python backends

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#517]
The functions in `batch_util.py` use custom multithreading to speed up calculations done using cirq interfaces.  However, this system causes issues when the cirq objects are actually interfaces to remote simulators or devices.  Since high performance is handled by the default qsim backend, we should remove this multithreading to give more freedom to the cirq backends.

**Comment by Mints97** [comment]
Does the default backend support multithreading? Will it automatically scale with the number of processors on my machine?

**Comment by zaqqwerty** [comment]
The default backend is [qsim](https://github.com/quantumlib/qsim), which automatically supports multithreading.  This issue is just about custom Cirq backends that call out to real hardware, where we let the given backend choose how to parallelize instead of dictating local multithreading (which can overwhelm some quantum computers).
