### ISSUE TITLE
GSOC21 Project Feasibility/Contribution

### ISSUE THREAD

**Issue by jakeywatson** [tensorflow/quantum#538]
Hi all, I'm looking to contribute, but it looks like the only tagged 'good first issue' is being worked on.

 I have a physics and computing background, and I'm also applying to GSOC21 so I thought this could be a good opportunity to do an 'out of the project list' application. If it doesn't get accepted I'd love to contribute anyway. 

What do you think?

**Comment by MichaelBroughton** [comment]
Hi @jakeywatson contributions are always welcome! Another good issue for contribution would be to add in some more C++ ops see: https://github.com/tensorflow/quantum/issues/380 . If you see anything you like, there's lots of good information there on what a typical op contribution looks like. We are in the middle of gearing up for our 0.5.0 release and after that we will probably start to scope out what features we want for 0.6.0.

I'm personally not too familiar with GSOC, but I would never say no to more contributors on TFQ :)

**Comment by jakeywatson** [comment]
Hi @MichaelBroughton, that looks good to me, I'm happy to take one of the ops from the [list](https://github.com/tensorflow/quantum/issues/380#issuecomment-782732880). I'll do it as a normal contribution, not with GSOC.

Are all of them still open? Also, which would you recommend, given that I'm new to TFQ? Really looking forward to the work :)

**Comment by MichaelBroughton** [comment]
I'd say either of `operator_matrix`, `operator_commutator` or `fidelity` would be a good place to start, with the easiest being fidelity (can probably get away without doing any C++ on it and just using calls to inner_product). Also left another comment on #380  thread that we might want to also support stabilizer simulation which would be the largest undertaking of all of these (likely requiring contributions both here and on the https://github.com/quantumlib/Stim repo).

**Comment by lockwo** [comment]
Can this issue be closed since it is no longer 2021?

**Comment by mhucka** [comment]
In the interest of prioritizing work on TensorFlow Quantum, I will close this issue as something that's been addressed. Please reopen this issue if that's incorrect.
