### ISSUE TITLE
Arithmetic expression outside of simple scalar multiplication is currently not supported

### ISSUE THREAD

**Issue by theRoughCode** [tensorflow/quantum#565]
I'm trying to simulate the bias and weights in a classical neuron using `sympy` as follows:

```python
qubits = cirq.GridQubit.rect(1, 1)
out_bits = qubits[-1:]
readouts = [cirq.Z(bit) for bit in out_bits]

encoding_params = sympy.symbols('enc0:{}'.format(self.input_dims))
weights = sympy.symbols('weights0:{}'.format(self.num_weights))
bias = sympy.symbols('bias0:{}'.format(self.num_bias))
params = [b + w * x for x, w, b in zip(encoding_params, weights[:3], bias[:3])]

circuit =cirq.Circuit(
      cirq.rx(params [0])(qubits[0]),
      cirq.ry(params [1])(qubits[0]),
      cirq.rz(params [2])(qubits[0])
  )


pqc = tfq.layers.ControlledPQC(circuit, readouts)
```

However, I'm getting the following error: `ValueError: Arithmetic expression outside of simple scalar multiplication is currently not supported. See serializer.py for more information.`

It seems like this sort of arithmetic manipulation of symbols is not supported yet. Is there a way around this?

**Comment by lockwo** [comment]
I believe that comes from the fact that your params looks like [bias0 + enc0*weights0, bias1 + enc1*weights1, bias2 + enc2*weights2] and only multiplication by a constant is allowed e.g. [10*weights0, 2*weights1, 4*weights2]. You could probably get around this with a custom layer. This seems to be similar to what  you are trying to achieve: 
```
class bias_layer(tf.keras.layers.Layer):
    def __init__(self, num_params, readout_ops):
        super(bias_layer, self).__init__()
        self.w = tf.Variable(initial_value=np.random.uniform(0, 2 * np.pi, (1, num_params)), dtype="float32", trainable=True)
        self.b = tf.Variable(initial_value=np.random.uniform(0, 2 * np.pi, (1, num_params)), dtype="float32", trainable=True)
        self.layer = tfq.layers.ControlledPQC(circuit, readout_ops)

    def call(self, inputs):
        return self.layer([inputs, self.w + self.b])
```

**Comment by MichaelBroughton** [comment]
Thanks for jumping on this @lockwo ! Building on that point, we only support scalar multiplication in circuit symbols and not much else. If you want to Compute any kind of complicated expression involving your symbol before putting it into a circuit, you should do so in TF. i.e.:
```python3
my_variable = <some tf.Tensor>
step1 = tf.math.log(my_variable)
step2 = step1 ** 2 + 10
step3 = step2 / 3.14
other_values = <some other tf.Tensor>
step4 = tf.math.cos(other_values)

final_inputs = tf.concat([step3, step4], ...)
a_pqc = tfq.layers.ControlledPQC(...)([..., final_inputs])
```
The above will feed in values to the symbols in your circuit that have had those transformations applied beforehand. We didn't want to find ourselves re-implementing all this baisc math stuff on our end when TF can already do it very reliably and quickly for us.

Does this help clear things up ?

**Comment by MichaelBroughton** [comment]
Going to close for now. Feel free to re-open if there's any more issues.

**Comment by theRoughCode** [comment]
That definitely helps, sorry for the late response!
