### ISSUE TITLE
Dependency mismatch

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#572]
TFQ 0.5 depends on "grpcio==1.30.0", but TF 2.4.1 depends on grpcio (>=1.32.0,<1.33.0).

Am using poetry to manage dependencies on another project, when trying to upgrade to tfq 0.5 I get the following error:
```
  SolverProblemError

  Because tensorflow (2.4.1) depends on grpcio (>=1.32.0,<1.33.0)
   and tensorflow-quantum (0.5.0) depends on grpcio (1.30.0), tensorflow (2.4.1) is incompatible with tensorflow-quantum (0.5.0).
```

**Comment by ryanhill1** [comment]
Yes, I ran into the same issue just now trying to run the install and import cells in the [MNIST tutorial notebook](https://www.tensorflow.org/quantum/tutorials/mnist).

**Comment by MichaelBroughton** [comment]
Strange.... It doesn't seem to lead to any breakages, despite the error. @zaqqwerty do you want to try a grpcio upgrade and see what happens ?
