### ISSUE TITLE
TF 2.5.0 Upgrade

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#583]
We recently tried to upgrade to 2.5.0 #568 , but ended up backing it out because there were some pretty serious performance drops. If we want to move forward with Python 3.9 support, we are going to need to fix this and upgrade.

**Comment by zaqqwerty** [comment]
[TFQ v0.6.0](https://github.com/tensorflow/quantum/releases/tag/v0.6.0) added support for TF 2.7.0
