### ISSUE TITLE
Installation Issue: _tfq_simulate_ops.so - undefined symbol

### ISSUE THREAD

**Issue by AnimeshSinha1309** [tensorflow/quantum#602]
## State of Install

I have followed all the steps on the [installation guide](https://github.com/tensorflow/quantum/blob/master/docs/install.md). First installed Tensorflow (crashed 3 times while building, but build completed in the end), everything works on the python shell. Then I installed tensorflow quantum, wheel file got built correctly, and all tests passed. 

But when I try to include it in the python shell, it raises an error `_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl14lts_2020_02_2511string_viewEPPKNS_6TensorE`

## Screenshot of the Issue

![image](https://user-images.githubusercontent.com/9739218/124674275-069a2680-ded8-11eb-9dab-4c3ef5f0d0ac.png)

**Comment by AnimeshSinha1309** [comment]
More issues, with more files. Shared object files. Restarting the python kernel gets me stuck here. This is a recurring issue now, and the `pauli_sum_pb2` issue vanished.
![image](https://user-images.githubusercontent.com/9739218/124658801-d8115100-dec1-11eb-99c6-8d31ac185b4c.png)

**Comment by lockwo** [comment]
I'm not sure the exact reason for you issue, but I've had similar problems when installing on an ubuntu WSL (everything installed error free, then crashed in the shell). I was able to resolve it by deleting and recreating the virtual environment (I think there was version conflicts with packages I had pre-installed that didn't throw an error). It may not be the same situation as yours, but it might be worth a shot.

**Comment by AnimeshSinha1309** [comment]
Did work for me, I deleted everything and reinstalled using the same wheel file. I am on Ubuntu and using conda environments. The issue seems to be more fundamental though, the name `pauli_sum_pb2` is never defined in the codebase, take a look [here](https://github.com/tensorflow/quantum/search?q=pauli_sum_pb2). But it's being called.

There has to be some TFQ proto magic that is making this work for everyone, I don't know what it so I can't debug yet.

**Comment by lockwo** [comment]
That's unfortunate that the deletion and pip installing didn't work. That's really as far as I can help (since I'm not a TFQ developer), but you can see the proto files (https://github.com/tensorflow/quantum/tree/master/tensorflow_quantum/core/proto) and work from there if that's the source of your problem. I don't know if this helps you at all, but this is the built `pauli_sum_pb2.py` file on my machine (for TFQ 0.5, but not the nightly build). 
```
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_quantum/core/proto/pauli_sum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_quantum/core/proto/pauli_sum.proto',
  package='tfq.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n-tensorflow_quantum/core/proto/pauli_sum.proto\x12\ttfq.proto\"/\n\x08PauliSum\x12#\n\x05terms\x18\x01 \x03(\x0b\x32\x14.tfq.proto.PauliTerm\"j\n\tPauliTerm\x12\x18\n\x10\x63oefficient_real\x18\x01 \x01(\x02\x12\x18\n\x10\x63oefficient_imag\x18\x02 \x01(\x02\x12)\n\x06paulis\x18\x03 \x03(\x0b\x32\x19.tfq.proto.PauliQubitPair\"6\n\x0ePauliQubitPair\x12\x10\n\x08qubit_id\x18\x01 \x01(\t\x12\x12\n\npauli_type\x18\x02 \x01(\tb\x06proto3')
)




_PAULISUM = _descriptor.Descriptor(
  name='PauliSum',
  full_name='tfq.proto.PauliSum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='terms', full_name='tfq.proto.PauliSum.terms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=107,
)


_PAULITERM = _descriptor.Descriptor(
  name='PauliTerm',
  full_name='tfq.proto.PauliTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coefficient_real', full_name='tfq.proto.PauliTerm.coefficient_real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coefficient_imag', full_name='tfq.proto.PauliTerm.coefficient_imag', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paulis', full_name='tfq.proto.PauliTerm.paulis', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=215,
)


_PAULIQUBITPAIR = _descriptor.Descriptor(
  name='PauliQubitPair',
  full_name='tfq.proto.PauliQubitPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qubit_id', full_name='tfq.proto.PauliQubitPair.qubit_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pauli_type', full_name='tfq.proto.PauliQubitPair.pauli_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=271,
)

_PAULISUM.fields_by_name['terms'].message_type = _PAULITERM
_PAULITERM.fields_by_name['paulis'].message_type = _PAULIQUBITPAIR
DESCRIPTOR.message_types_by_name['PauliSum'] = _PAULISUM
DESCRIPTOR.message_types_by_name['PauliTerm'] = _PAULITERM
DESCRIPTOR.message_types_by_name['PauliQubitPair'] = _PAULIQUBITPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PauliSum = _reflection.GeneratedProtocolMessageType('PauliSum', (_message.Message,), {
  'DESCRIPTOR' : _PAULISUM,
  '__module__' : 'tensorflow_quantum.core.proto.pauli_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.PauliSum)
  })
_sym_db.RegisterMessage(PauliSum)

PauliTerm = _reflection.GeneratedProtocolMessageType('PauliTerm', (_message.Message,), {
  'DESCRIPTOR' : _PAULITERM,
  '__module__' : 'tensorflow_quantum.core.proto.pauli_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.PauliTerm)
  })
_sym_db.RegisterMessage(PauliTerm)

PauliQubitPair = _reflection.GeneratedProtocolMessageType('PauliQubitPair', (_message.Message,), {
  'DESCRIPTOR' : _PAULIQUBITPAIR,
  '__module__' : 'tensorflow_quantum.core.proto.pauli_sum_pb2'
  # @@protoc_insertion_point(class_scope:tfq.proto.PauliQubitPair)
  })
_sym_db.RegisterMessage(PauliQubitPair)


# @@protoc_insertion_point(module_scope)
```

**Comment by AnimeshSinha1309** [comment]
Okay, that was not the bug. The major issue was a missing symbol. 
![image](https://user-images.githubusercontent.com/9739218/124674217-f1bd9300-ded7-11eb-8ae5-d5452180a966.png)

I am editing the issue title to correctly reflect the problem.

**Comment by MichaelBroughton** [comment]
Hi @AnimeshSinha1309 thanks for raising the issue and thanks for coming out to the sync today. Would you be able to provide a little more detail on which OS you are using as well as which version of python , tensorflow and other related libraries you have on your system while installing so that we can try to reproduce the error on our end ?

**Comment by AnimeshSinha1309** [comment]
Thanks Michael. I am working on Ubuntu 20.04, Python 3.8.10, Tensorflow 2.4.1. The rest of the libraries were installed in a virtual environment from `requirements.txt`.
It might be an issue with the many environments, since there were several builds of Tensorflow on Conda and Pip. I am working off a fresh install now, but Tensorflow is taking days to compile.

**Comment by AnimeshSinha1309** [comment]
I didn't build Tensorflow from source, just downloaded from pip. Things work now. I installed Tensorflow in many rounds, the build process cached some actions, maybe I had used incorrect compilation flags in some of them.
Anyways, closing this issue, it had something to do with the Tensorflow version and build flags for sure. Thanks for the help.
