### ISSUE TITLE
ValueError: Attempted to serialize circuit that don't use only cirq.GridQubits

### ISSUE THREAD

**Issue by andreasfrin** [tensorflow/quantum#609]
tfq doesnt like cirq.LineQubit layout required in ionq circuits, tfq.layers.SampledExpectation throws

ValueError: Attempted to serialize circuit that don't use only cirq.GridQubits.

**Comment by lockwo** [comment]
Given the specificity of the error message I would assume this is intended functionality. Is there a need to use LineQubits over GridQubits?

**Comment by andreasfrin** [comment]
ionq requires cirq.LineQubit layout

**Comment by MichaelBroughton** [comment]
This is an intended error. We don't currently support LineQubits like @lockwo mentioned. If it's not as easy as just switching from linequbits to GridQubits, then the fix here might be a little more involved.

**Comment by HuangChiEn** [comment]
I also got the same error by applying the NamedQubit. 
I have no idea how hard to support another type of Qubits layout, but it may allow the circuit more readable. For example, the tutorial hello_many_world.py is make use of the GridQubits to declare the q_0, q_1, while the GridQubits layout let the output of SVGCiruit become meaningless.
(0, 0) -----o---- \ omit
                 |
(0, 1) ---- X---- \ omit

When I use NamedQubit, it makes it readable in any circuit output.
cnt_bit ----o---- \ omit
                  |
tar_bit  --- X--- \ omit

**Comment by MichaelBroughton** [comment]
Opened #611 for anyone interested in tackling a fix for this issue. For now the workaround is to use GridQubits as that is the only qubit form that is completely supported by TFQ. Going to close for now.

**Comment by raoufdridi** [comment]
any insight how to fix this?

**Comment by HuangChiEn** [comment]
> Opened #611 for anyone interested in tackling a fix for this issue. For now the workaround is to use GridQubits as that is the only qubit form that is completely supported by TFQ. Going to close for now.

I know, so I commented the NameQubit (replace into GridQubit) and everything went fine ~ ~
I just want to point out supporting (tfq) other qubit layout may not be the trivial issue ~ ~
