### ISSUE TITLE
Add TFQ whitepaper to readme after release

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#61]
Comment from @jaeyoo 
"
It is conventional to write a paper on TensorFlow & TensorFlow addon libraries.

For example, TensorFlow Probability also has its own paper aligned with its release, and the following message is inside README.md of its GitHub repo. [here](https://github.com/tensorflow/probability)

```
If you use TensorFlow Probability in a paper, please cite:

TensorFlow Distributions. Joshua V. Dillon, Ian Langmore, Dustin Tran, Eugene Brevdo, Srinivas Vasudevan, Dave Moore, Brian Patton, Alex Alemi, Matt Hoffman, Rif A. Saurous. arXiv preprint arXiv:1711.10604, 2017.
```
References:
TensorFlow [arXiv](https://arxiv.org/abs/1603.04467)
TensorNetwork [arXiv](https://arxiv.org/abs/1905.01331)
TensorFlow.js [arXiv](https://arxiv.org/abs/1901.05350v1)
TensorFlow Distributions [arXiv](https://arxiv.org/pdf/1711.10604.pdf)
"

**Comment by MichaelBroughton** [comment]
We have a link in the `README.md` now. Closing.
