### ISSUE TITLE
Fix code formatting in docstrings

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#65]
Comment from @MichaelBroughton 
"Right now internal docstring renders screw up some of the code we have. Will need to fiddle with layers and differentiators to get this fixed. This also includes cleaning up the descriptions in the `__init__.py` modules so taht they describe in more detail what they are as they do get rendered."

Comment from @jaeyoo 
"`tfdevsite`/quantum/api_docs/python/tfq/layers/Expectation

As you can see, some codes have no line space, but others have 1 empty line space between lines. Is it intended? If not, we need to unify them into the one way."

**Comment by MichaelBroughton** [comment]
This got fixed a while back.
