### ISSUE TITLE
Installation issues in Jupyterlab on Rigetti QCS

### ISSUE THREAD

**Issue by tom-genmat** [tensorflow/quantum#656]
Hey folks, 

Tried to get this set up on Rigetti QCS right now and am having issues building. 

I can clone the repo but cant install via source since I cant `sudo apt...` or install Bazel as Rigetti manages the environment

Working to install via pip I run into a few issues. I've manually installed all the dependencies but keep getting this issue when trying to build tfq 0.5.1:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
tensorflow-quantum 0.5.1 requires cirq==0.11.0, but you have cirq 0.12.0 which is incompatible.
```

Which is weird since the requirements.txt show 0.12.0 as needed. Is there something not alinging with the pip package or is there another way to do this from source without bazel? 

I have tried with 0.11.0 but then I get the issue: 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cirq-web 0.12.0 requires cirq-core==0.12.0, but you have cirq-core 0.11.0 which is incompatible.
cirq-rigetti 0.12.0 requires cirq-core==0.12.0, but you have cirq-core 0.11.0 which is incompatible.
cirq-pasqal 0.12.0 requires cirq-core==0.12.0, but you have cirq-core 0.11.0 which is incompatible.
cirq-ionq 0.12.0 requires cirq-core==0.12.0, but you have cirq-core 0.11.0 which is incompatible.
cirq-aqt 0.12.0 requires cirq-core==0.12.0, but you have cirq-core 0.11.0 which is incompatible.
```

We're hoping to run tfq + cirq on Rigetti's latest devices but we need cirq 0.12.0 to make that work. 

I am following up with them as well but suspect they aren't going to be as familiar. 

Please let me know! 
Thanks, 
Tom

**Comment by lockwo** [comment]
The TFQ 0.5.1 has `cirq==0.11.0`. The nightly build is `cirq == 0.13.1`. I'm not sure which requirements.txt shows 0.12.0 (I see https://github.com/tensorflow/quantum/blob/051_cp/requirements.txt and https://github.com/tensorflow/quantum/blob/master/requirements.txt). There isn't a version of TFQ that has `cirq == 0.12.0` as 
far as I can tell (see https://github.com/tensorflow/quantum/commits/master/requirements.txt). It might still be possible to make it work with that hard requirement, but someone more knowledgeable on the builds will have to provide more insight.

**Comment by tom-genmat** [comment]
Ah yes that is my mistake. I meant 0.13.1. 

I'll look at installing the nightly build to see how that goes. Thank you so much!

**Comment by tom-genmat** [comment]
This works. Please disregard issue!
