### ISSUE TITLE
The version of tensorflow and protobuf.

### ISSUE THREAD

**Issue by XxX2009** [tensorflow/quantum#671]
Firstly, I installed tensorflow==2.4.1 with `pip install tensorflow==2.4.1`. It's ok.
then I installed tensorflow-quantum with `pip install -q tensorflow-quantum`. There was an error following the figure:
![error1](https://user-images.githubusercontent.com/72677578/154232680-79dd4473-2d6b-453b-841c-4e4164943dfe.png)
So, I uninstalled protobuf==3.8.0 and installed protobuf==3.9.2, but there was still an error following the figure:
![error2](https://user-images.githubusercontent.com/72677578/154233427-9119d90c-51f5-4e5e-93e5-98c2bd074b37.png)
I am really confused now, please help me getting rid of this.

**Comment by XxX2009** [comment]
Thank you for your help. But I am sorry to tell you that I've got new problem.
FIrstly, I created an environment with python 3.8 and tried to install the latest version of TFQ. As your advice, I needed TF 2.7.0 and cirq >= 0.13.1. After installing TF 2.7.0 and cirq == 0.13.1, I installed TFQ with `pip install -U tensorflow-quantum`, but it showed the following figure:
![error3](https://user-images.githubusercontent.com/72677578/154419984-eba965d9-59ed-4e8c-b867-2724492e0780.png)
Then, I created another environment with python 3.6.2 and installed TF 2.1.0 and TFQ 0.3.1. It works. However, when I run the code of noise_suppression.ipynb. There was an error following the figure:
![error4](https://user-images.githubusercontent.com/72677578/154421868-d84a9914-493a-40ba-adaf-864b740b661a.png)
As your answer at [https://github.com/tensorflow/quantum/issues/670#issuecomment-1039894771](url), I tried to fix the problem with `pip install -U tensorflow-quantum`. But it did not work. 
Finally, thank you for your patience.

> There appears to be a number of version mismatches. The latest version of tensorflow quantum requires tensorflow==2.7.0 and cirq >= 0.13.1. So TF 2.4.1 and cirq 0.8 will cause problems. TFQ 0.5.1 is compatible with TF 2.4.1 but requires cirq==0.11.0. I believe cirq 0.8.0 is compatible with TFQ 0.3.1 which works with TF 2.1.0. If you want the latest version of TFQ, just make a new environment and follow the install instructions https://www.tensorflow.org/quantum/install.

**Comment by lockwo** [comment]
The tutorial won't work with 0.3.1 because noise support was added in 0.5. As for the first error, are you by any chance using windows?

**Comment by XxX2009** [comment]
> The tutorial won't work with 0.3.1 because noise support was added in 0.5. As for the first error, are you by any chance using windows?
I am using windows 10. And  could you tell me what should I do?

**Comment by lockwo** [comment]
TFQ 0.3 is the latest version supported on windows (hence why you cannot update it on windows using pip -U). When I am working on my laptop with windows, I use WSL to work with current TFQ versions. Google colab is also a good option.

**Comment by MichaelBroughton** [comment]
Thanks for clearing this up @lockwo ! To confirm we do not currently support windows in our latest releases and in order to upgrade to the latest version, one does need to use a mac or linux platform.

**Comment by mhucka** [comment]
In the interest of prioritizing work on TensorFlow Quantum, I will close this issue as something that's been addressed. Please reopen this issue if that's incorrect.
