### ISSUE TITLE
Upgrade full build pipeline to Bazel 2.0 and TF 2.2.0

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#68]
The current bazel version for a given TF version can be found [here](https://www.tensorflow.org/install/source#tested_build_configurations)

**Comment by MichaelBroughton** [comment]
It looks like TF and Bazel have made a serious leap to bazel 2.0.0. When we upgrade our support to tf 2.2 we should coordinate this upgrade with bazel. Things will likely break a lot :)

**Comment by MichaelBroughton** [comment]
This has been resolved now with: #340
