### ISSUE TITLE
module 'cirq.study' has no attribute 'ResultDict'

### ISSUE THREAD

**Issue by RubensZimbres** [tensorflow/quantum#708]
Hello, I'm following the Colab notebook at https://www.tensorflow.org/quantum/tutorials/hello_many_worlds, downloaded the code and I'm running on Visual Studio. When I installed cirq for the first time, it worked. Now that I installed tensorflow-quantum==0.72 and tensorflow==2.7.0 I get the above error.

I created a Python 3.8 environment in Anaconda and installed tensorflow==2.7.0 and tensorflow-quantum==0.7.2

When I run:

`import simpy
import cirq`

I get the following error:

`AttributeError: module 'cirq.study' has no attribute 'ResultDict'`

Also, 
`tensorflow-quantum 0.7.2 requires cirq-core==0.13.1, but you have cirq-core 1.0.0 which is incompatible.
tensorflow-quantum 0.7.2 requires protobuf==3.17.3, but you have protobuf 3.20.1 which is incompatible.`

`! pip install cirq-core==0.13.1
! pip install protobuf==3.17.3`

But it didn't work.

Details of the error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 import tensorflow as tf
----> 2 import tensorflow_quantum as tfq
      4 import sympy
      5 import cirq

File ~/.local/lib/python3.8/site-packages/tensorflow_quantum/__init__.py:18, in <module>
     15 """Module functions for tensorflow_quantum.*"""
     17 # Import basic ops and op getters.
---> 18 from tensorflow_quantum.core import (append_circuit, get_expectation_op,
     19                                      get_sampled_expectation_op,
     20                                      get_sampling_op, get_state_op,
     21                                      get_unitary_op, padded_to_ragged,
     22                                      padded_to_ragged2d, resolve_parameters)
     24 # Import math ops.
     25 from tensorflow_quantum.core import math_ops as math

File ~/.local/lib/python3.8/site-packages/tensorflow_quantum/core/__init__.py:17, in <module>
     15 """Imports to tensorflow_quantum.core.* level."""
     16 # Import getters for constructing ops.
---> 17 from tensorflow_quantum.core.ops import (get_expectation_op,
     18                                          get_sampled_expectation_op,
     19                                          get_sampling_op, get_state_op,
     20                                          get_unitary_op)
     21 # Import regular ops.
     22 from tensorflow_quantum.core.ops import (append_circuit, padded_to_ragged,
     23                                          padded_to_ragged2d, resolve_parameters)

File ~/.local/lib/python3.8/site-packages/tensorflow_quantum/core/ops/__init__.py:18, in <module>
     15 """Module for tfq.core.ops.*"""
     17 # Import getters for constructing ops.
---> 18 from tensorflow_quantum.core.ops.circuit_execution_ops import (
     19     get_expectation_op, get_sampled_expectation_op, get_sampling_op,
     20     get_state_op)
     22 from tensorflow_quantum.core.ops.tfq_unitary_op import get_unitary_op
     23 from tensorflow_quantum.core.ops.tfq_utility_ops import (append_circuit,
     24                                                          padded_to_ragged,
     25                                                          padded_to_ragged2d,
     26                                                          resolve_parameters)

File ~/.local/lib/python3.8/site-packages/tensorflow_quantum/core/ops/circuit_execution_ops.py:18, in <module>
     15 """A module for user-facing generators of tfq ops."""
     16 import enum
---> 18 import cirq
     20 from tensorflow_quantum.core.ops import (cirq_ops, tfq_simulate_ops,
     21                                          tfq_utility_ops)
     22 from tensorflow_quantum.python import quantum_context

File ~/.local/lib/python3.8/site-packages/cirq/__init__.py:624, in <module>
    616 # pylint: enable=redefined-builtin
    617 
    618 # Unflattened sub-modules.
    620 from cirq import (
    621     testing,
    622 )
--> 624 _compat.deprecated_submodule(
    625     new_module_name='cirq_google',
    626     old_parent=__name__,
    627     old_child='google',
    628     deadline="v0.14",
    629     create_attribute=True,
    630 )
    632 _compat.deprecated_submodule(
    633     new_module_name='cirq_aqt',
    634     old_parent=__name__,
   (...)
    637     create_attribute=True,
    638 )
    641 _compat.deprecated_submodule(
    642     new_module_name='cirq_ionq',
    643     old_parent=__name__,
   (...)
    646     create_attribute=True,
    647 )

File ~/.local/lib/python3.8/site-packages/cirq/_compat.py:626, in deprecated_submodule(new_module_name, old_parent, old_child, deadline, create_attribute)
    624 if create_attribute:
    625     try:
--> 626         new_module = importlib.import_module(new_module_name)
    627         _setup_deprecated_submodule_attribute(
    628             new_module_name, old_parent, old_child, deadline, new_module
    629         )
    630     except ImportError as ex:

File /usr/lib/python3.8/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File ~/.local/lib/python3.8/site-packages/cirq_google/__init__.py:23, in <module>
     19 from cirq_google import api
     21 from cirq_google._version import __version__
---> 23 from cirq_google.calibration import (
     24     ALL_ANGLES_FLOQUET_PHASED_FSIM_CHARACTERIZATION,
     25     CircuitWithCalibration,
     26     FloquetPhasedFSimCalibrationOptions,
     27     FloquetPhasedFSimCalibrationRequest,
     28     FSimPhaseCorrections,
     29     PhasedFSimCalibrationError,
     30     PhasedFSimCalibrationOptions,
     31     PhasedFSimCalibrationRequest,
     32     PhasedFSimCalibrationResult,
     33     PhasedFSimCharacterization,
     34     PhasedFSimEngineSimulator,
     35     XEBPhasedFSimCalibrationOptions,
     36     XEBPhasedFSimCalibrationRequest,
     37     LocalXEBPhasedFSimCalibrationOptions,
     38     LocalXEBPhasedFSimCalibrationRequest,
     39     SQRT_ISWAP_INV_PARAMETERS,
     40     THETA_ZETA_GAMMA_FLOQUET_PHASED_FSIM_CHARACTERIZATION,
     41     make_zeta_chi_gamma_compensation_for_moments,
     42     make_zeta_chi_gamma_compensation_for_operations,
     43     merge_matching_results,
     44     prepare_characterization_for_circuits_moments,
     45     prepare_floquet_characterization_for_moments,
     46     prepare_characterization_for_moments,
     47     prepare_floquet_characterization_for_moment,
     48     prepare_characterization_for_moment,
     49     prepare_floquet_characterization_for_operations,
     50     prepare_characterization_for_operations,
     51     run_calibrations,
     52     run_floquet_characterization_for_moments,
     53     run_zeta_chi_gamma_compensation_for_moments,
     54     try_convert_sqrt_iswap_to_fsim,
     55     WITHOUT_CHI_FLOQUET_PHASED_FSIM_CHARACTERIZATION,
     56 )
     58 from cirq_google.devices import (
     59     GoogleNoiseProperties,
     60     GridDevice,
   (...)
     63     Sycamore23,
     64 )
     66 from cirq_google.engine import (
     67     Calibration,
     68     CalibrationLayer,
   (...)
     82     noise_properties_from_calibration,
     83 )

File ~/.local/lib/python3.8/site-packages/cirq_google/calibration/__init__.py:17, in <module>
      1 # Copyright 2021 The Cirq Developers
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 """Functions for calling the calibration API and characterizing qubits."""
---> 17 from cirq_google.calibration.engine_simulator import PhasedFSimEngineSimulator
     19 from cirq_google.calibration.phased_fsim import (
     20     ALL_ANGLES_FLOQUET_PHASED_FSIM_CHARACTERIZATION,
     21     FloquetPhasedFSimCalibrationOptions,
   (...)
     38     try_convert_syc_or_sqrt_iswap_to_fsim,
     39 )
     41 from cirq_google.calibration.workflow import (
     42     CircuitWithCalibration,
     43     FSimPhaseCorrections,
   (...)
     55     run_zeta_chi_gamma_compensation_for_moments,
     56 )

File ~/.local/lib/python3.8/site-packages/cirq_google/calibration/engine_simulator.py:32, in <module>
     30 import cirq
     31 from cirq import value
---> 32 from cirq_google.calibration.phased_fsim import (
     33     FloquetPhasedFSimCalibrationRequest,
     34     PhaseCalibratedFSimGate,
     35     IncompatibleMomentError,
     36     PhasedFSimCalibrationRequest,
     37     PhasedFSimCalibrationResult,
     38     PhasedFSimCharacterization,
     39     SQRT_ISWAP_INV_PARAMETERS,
     40     try_convert_gate_to_fsim,
     41     try_convert_sqrt_iswap_to_fsim,
     42 )
     44 ParametersDriftGenerator = Callable[[cirq.Qid, cirq.Qid, cirq.FSimGate], PhasedFSimCharacterization]
     45 PhasedFsimDictParameters = Dict[
     46     Tuple[cirq.Qid, cirq.Qid], Union[Dict[str, float], PhasedFSimCharacterization]
     47 ]

File ~/.local/lib/python3.8/site-packages/cirq_google/calibration/phased_fsim.py:44, in <module>
     42 from cirq.experiments.xeb_fitting import XEBPhasedFSimCharacterizationOptions
     43 from cirq_google.api import v2
---> 44 from cirq_google.engine import (
     45     Calibration,
     46     CalibrationLayer,
     47     CalibrationResult,
     48     Engine,
     49     EngineJob,
     50     util,
     51 )
     52 from cirq_google.ops import FSimGateFamily, SycamoreGate
     54 if TYPE_CHECKING:

File ~/.local/lib/python3.8/site-packages/cirq_google/engine/__init__.py:18, in <module>
      1 # Copyright 2018 The Cirq Developers
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 """Client for running on Google's Quantum Engine.
     16 """
---> 18 from cirq_google.engine.abstract_engine import AbstractEngine
     20 from cirq_google.engine.abstract_job import AbstractJob
     22 from cirq_google.engine.abstract_processor import AbstractProcessor

File ~/.local/lib/python3.8/site-packages/cirq_google/engine/abstract_engine.py:26, in <module>
     24 import cirq
     25 from cirq_google.cloud import quantum
---> 26 from cirq_google.engine import abstract_job, abstract_program, abstract_processor
     28 VALID_DATE_TYPE = Union[datetime.datetime, datetime.date]
     31 class AbstractEngine(abc.ABC):

File ~/.local/lib/python3.8/site-packages/cirq_google/engine/abstract_job.py:23, in <module>
     21 import cirq
     22 from cirq_google.cloud import quantum
---> 23 from cirq_google.engine.engine_result import EngineResult
     25 if TYPE_CHECKING:
     26     import datetime

File ~/.local/lib/python3.8/site-packages/cirq_google/engine/engine_result.py:25, in <module>
     21 if TYPE_CHECKING:
     22     import cirq
---> 25 class EngineResult(study.ResultDict):
     26     """A ResultDict with additional job metadata.
     27 
     28     Please see the documentation for `cirq.ResultDict` for more information.
   (...)
     32         job_finished_time: A timestamp for when the job finished.
     33     """
     35     def __init__(
     36         self,
     37         *,  # Forces keyword args.
   (...)
     42         records: Optional[Mapping[str, np.ndarray]] = None,
     43     ):

AttributeError: module 'cirq.study' has no attribute 'ResultDict'`

**Comment by lockwo** [comment]
Are you on windows or Linux?

**Comment by RubensZimbres** [comment]
I'm on Linux, Ubuntu 20.04. I managed to get rid of the error, but now I'm getting:

`AttributeError: partially initialized module 'cirq' has no attribute 'TwoQubitCompilationTargetGateset' (most likely due to a circular import)`

`pip-list`

Package                      Version
---------------------------- ---------
absl-py                      1.2.0
asttokens                    2.0.5
astunparse                   1.6.3
attrs                        20.3.0
backcall                     0.2.0
cachetools                   4.2.4
certifi                      2022.6.15
charset-normalizer           2.1.0
cirq-aqt                     1.0.0
cirq-core                    0.13.1
cirq-google                  0.13.1
cirq-ionq                    1.0.0
cirq-pasqal                  1.0.0
cirq-rigetti                 1.0.0
cirq-web                     1.0.0
cycler                       0.11.0
debugpy                      1.6.2
decorator                    5.1.1
duet                         0.2.7
entrypoints                  0.4
executing                    0.9.1
flatbuffers                  2.0
fonttools                    4.34.4
freezegun                    0.3.15
gast                         0.4.0
google-api-core              1.21.0
google-api-python-client     1.11.0
google-auth                  1.18.0
google-auth-httplib2         0.1.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
googleapis-common-protos     1.56.0
grpcio                       1.47.0
h11                          0.9.0
h5py                         3.7.0
httpcore                     0.11.1
httplib2                     0.20.4
httpx                        0.15.5
idna                         3.3
importlib-metadata           4.12.0
ipykernel                    6.15.1
ipython                      8.4.0
iso8601                      1.0.2
jedi                         0.18.1
jupyter-client               7.3.4
jupyter-core                 4.11.1
keras                        2.7.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
lark                         0.11.3
libclang                     14.0.6
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.5.2
matplotlib-inline            0.1.3
mpmath                       1.2.1
msgpack                      0.6.2
nest-asyncio                 1.5.5
networkx                     2.8.5
numpy                        1.23.1
oauthlib                     3.2.0
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.4.3
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.2.0
pip                          22.1.2
prompt-toolkit               3.0.30
proto-plus                   1.20.6
protobuf                     3.17.3
psutil                       5.9.1
ptyprocess                   0.7.0
pure-eval                    0.2.2
py                           1.11.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pydantic                     1.9.1
Pygments                     2.12.0
PyJWT                        2.4.0
pyparsing                    3.0.9
pyquil                       3.2.1
python-dateutil              2.8.2
python-rapidjson             1.8
pytz                         2022.1
pyzmq                        23.2.0
qcs-api-client               0.21.1
requests                     2.28.1
requests-oauthlib            1.3.1
retry                        0.9.2
retrying                     1.3.3
rfc3339                      6.2
rfc3986                      1.5.0
rpcq                         3.10.0
rsa                          4.9
ruamel.yaml                  0.17.21
ruamel.yaml.clib             0.2.6
scipy                        1.9.0
setuptools                   63.4.2
six                          1.16.0
sniffio                      1.2.0
sortedcontainers             2.4.0
stack-data                   0.3.0
sympy                        1.8
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.0
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.26.0
tensorflow-quantum           0.7.2
termcolor                    1.1.0
toml                         0.10.2
tornado                      6.2
tqdm                         4.64.0
traitlets                    5.3.0
typing_extensions            4.3.0
uritemplate                  3.0.1
urllib3                      1.26.11
wcwidth                      0.2.5
Werkzeug                     2.2.1
wheel                        0.37.1
wrapt                        1.14.1
zipp                         3.8.1

**Comment by lockwo** [comment]
I haven't done much with the 0.7 versions, I can look into more if there is something specific you are looking to use the 0.7 version for. If not, I might recommend installing the latest release build (0.6.1, https://github.com/tensorflow/quantum/releases/tag/v0.6.1). I believe most of the changes from 0.6 to 0.7 are minor e.g. bumping versions (for cirq and qsim).

**Comment by RubensZimbres** [comment]
Thanks you very much, tensorflow==0.6.1 worked, no errors.
