### ISSUE TITLE
Query regarding the MNIST tutorial

### ISSUE THREAD

**Issue by sauravtii** [tensorflow/quantum#720]
Does [this](https://www.tensorflow.org/quantum/tutorials/mnist) tutorial create a quantum neural network model that can be deployed on an actual quantum computer ?
If not, what changes needs to be made to that model so that it can be deployed on an actual quantum computer ?

**Comment by lockwo** [comment]
Yea you could deploy it on a QC. Depending on what QC you are using, might have to do a little converting, but nothing impossible.

**Comment by sauravtii** [comment]
Okay, thanks.

**Comment by lockwo** [comment]
You are welcome. Feel free to close the issue if there is nothing else.

**Comment by saurav935** [comment]
After completing the tutorial, I noticed that the quantum neural network model is not simulated using anything. How can I do that ?
