### ISSUE TITLE
Encoding the images to 0s and 1s

### ISSUE THREAD

**Issue by sauravtii** [tensorflow/quantum#722]
Hi,
In [this](https://www.tensorflow.org/quantum/tutorials/mnist#:~:text=At%20the%20same%20time%20convert%20the%20label%2C%20y%2C%20to%20boolean%3A%20True%20for%203%20and%20False%20for%206.) tutorial, when we write the code to keep 3s and 6s we are also converting them to True and False.

Will it work if we convert it to 0s and 1s instead of True and False ?

If not, why ?

**Comment by lockwo** [comment]
Yea it should work

**Comment by sauravtii** [comment]
Okay, thanks.
