### ISSUE TITLE
How to simulate a QNN ?

### ISSUE THREAD

**Issue by saurav935** [tensorflow/quantum#723]
Hi,

After completing [this](https://www.tensorflow.org/quantum/tutorials/mnist) tutorial, I noticed that the quantum neural network model is not simulated using anything. How can I do that ?

**Comment by lockwo** [comment]
It is simulated, what gives the impression it isn't?

**Comment by saurav935** [comment]
Can you tell me at what point is the quantum neural network simulated ?

**Comment by lockwo** [comment]
Every time the model is executed (in training or testing) simulation occurs. The PQC layer manages this simulation.

**Comment by saurav935** [comment]
Ohh okay, I understand now. Thank you!
