### ISSUE TITLE
How are the predictions done?

### ISSUE THREAD

**Issue by sauravtii** [tensorflow/quantum#725]
In this [tutorial](https://www.tensorflow.org/quantum/tutorials/mnist), I did the predictions and got the following output

```
predictions = model.predict(x=x_test_tfcirc)
for i in range(0,20):
     print(round(predictions[i][0]))

Output:

1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
```

Here, it basically means that -1 means the image is of digit-3 and 1 means that the image is of digit-6, right ?

**Comment by lockwo** [comment]
Yes

**Comment by sauravtii** [comment]
Thanks!
