### ISSUE TITLE
How to use a QNN with encrypted data?

### ISSUE THREAD

**Issue by sauravtii** [tensorflow/quantum#731]
Hi,

How can I use the model mentioned in [this](https://www.tensorflow.org/quantum/tutorials/mnist) tutorial for [this](https://github.com/facebookresearch/CrypTen/blob/main/tutorials/Tutorial_4_Classification_with_Encrypted_Neural_Networks.ipynb) use case?

**Comment by lockwo** [comment]
I'm not really sure what the question is, just copy the model setup over and create a classical to quantum data conversion function and you should be good to go

**Comment by lockwo** [comment]
Yes, you can save and load weights the same as other TF models

**Comment by sauravtii** [comment]
Okay, by converting to Tensorflow do you mean converting CyPten code to tensorflow?

**Comment by sauravtii** [comment]
Okay, thanks!
And as you meantioned that the QNN model can be saved, can you tell how can I achieve that ?
I mean, saving the model after completing the training in the same way as a normal TF model, right?

**Comment by lockwo** [comment]
Yes, save_weights and load_weights are what I use

**Comment by sauravtii** [comment]
Okay, thank you for your response!

**Comment by mhucka** [comment]
It looks like this issue was answered and simply never closed. Closing it now.

(@lockwo Thank you for your answers here, and in the dozens of other issues where you've provided answers!)

**Comment by lockwo** [comment]
Happy to help :). I was quite the TFQ user back in the day (I even made quite some videos on it https://www.youtube.com/watch?v=0L_nAXtKicQ&list=PL91jA61XuCICSnv3DWhhNzOpiej4rX8Ea)
