### ISSUE TITLE
Pypi package versions

### ISSUE THREAD

**Issue by marcodelapierre** [tensorflow/quantum#734]
Hi, are you planning to release source tarballs here and on pypi, for versions 0.7.0, 0.7.1, 0.7.2 and future ones?

Thanks in advance, Marco

**Comment by mhucka** [comment]
I realize this issue is almost 2 years old, and basically has been answered by the fact that releases have indeed been provided here and on PyPI, but to answer the question more fully: yes, the plan is to continue to provide releases here and on PyPI.
