### ISSUE TITLE
All GitHub Code links are broken on website

### ISSUE THREAD

**Issue by lockwo** [tensorflow/quantum#741]
If you click the "View source on Github" button on any (that I have tested) of the TFQ functions on the website, you get a link that throws a 404 error. E.g. https://www.tensorflow.org/quantum/api_docs/python/tfq/datasets/tfi_chain -> https://github.com/tensorflow/quantum/blob/v0.7.2/tensorflow_quantum/datasets/spin_system.py#L94-L322. Looks like this is because they all point to a v0.7.2 which doesn't seem to be a branch, might be fixable with just changes to 0.6.2 (not sure if the line numbers are the same though).

**Comment by MichaelBroughton** [comment]
Just published a v0.7.2 release and verified the fix. Sorry for the interruption!
