### ISSUE TITLE
Is the parameters input in the same manner for two different `tfq.layers`?

### ISSUE THREAD

**Issue by Shuhul24** [tensorflow/quantum#746]
I am using two different layers: `tfq.layers.ControlledPQC` and `tfq.layers.State`. But the circuit, parameter symbols and parameters values are same. Is the manner in which these parameter values / weights get distributed same for evaluating `tfq.layers.ControlledPQC` and `tfq.layers.State`?

**Comment by lockwo** [comment]
For state, the user explicitly maps the parameter names and their values, assuming the parameter names are the same in the ControlledPQC, then yes (also true if you specify the names in values to the ControlledPQC)

**Comment by mhucka** [comment]
In the interest of prioritizing work on TensorFlow Quantum, I will close this issue as something that's been addressed. Please reopen this issue if that's incorrect.
