### ISSUE TITLE
Unrecognized program type: <clas 'keras.engine.functional.functional'>

### ISSUE THREAD

**Issue by deepquantum88** [tensorflow/quantum#751]
I was trying to run simple quantum circuit performing binary classification on processors "rainbow and weber", but it throws an error. Is there any short example performing machine learning task on quantum virtual machine? any help

**Comment by lockwo** [comment]
Is TFQ supposed to be compatible with QVM (ie does QVM have documentation on it)? Since I imagine the QVM is basically just a different kind of cirq backend, if specifying it as a backend doesn’t work I would guess it isn’t supported.

**Comment by deepquantum88** [comment]
Thank you for you response. I follows your youtube videos related to tfq cirq implementations. :)
as we perform QML tasks on ibmq real devices. I am planning to use TFQ PQC on QVM.

**Comment by lockwo** [comment]
Looking at QVM I suspect you will have to write some interfacing code, I wasn't able to get QVM working trivially as a normal backend. You can see examples of how the cirq backend here: https://github.com/tensorflow/quantum/blob/master/tensorflow_quantum/core/ops/circuit_execution_ops.py.

**Comment by mhucka** [comment]
@deepquantum88 This issue has regretfully sat unanswered for a long time. Is it still relevant, or can it be closed?
