### ISSUE TITLE
_tfq_simulate_ops.so cannot open shared file

### ISSUE THREAD

**Issue by deepquantum88** [tensorflow/quantum#757]
Hi,

I am installing TFQ (0.7.2) on python=3.9.7 version and TensorFlow 2.11.0, protobuf=3.17.3. But throws an error.
Earlier I worked with TFQ (0.7.2) with python 3.8.16 and TF= 2.7.0. It worked fine.

But now i have to use python=3.9 and it throws an error of file _tfq_simulate_ops.so.

Please help.

**Comment by lockwo** [comment]
I don't think 2.11.0 support is finalized yet (see https://github.com/tensorflow/quantum/pull/756 and https://github.com/tensorflow/quantum/pull/755). When it is finalized it will be through TFQ nightly, 0.7.2 requires TF 2.7.0 (see the requirements file for 0.7.2: https://github.com/tensorflow/quantum/blob/v0.7.2/requirements.txt#L8)

**Comment by deepquantum88** [comment]
can you please specify the steps to install with bazel. I checked tfq website. and installed bazel 5.3.0. But not sure how to make it compatible tf2.11.0 and tfq with bazel.

**Comment by deepquantum88** [comment]
I tried installing but it throws an error of undefined symbol _ZNK10tensorflow80p....

**Comment by lockwo** [comment]
Hmmm there are probably other issues in TFQ that need to be fixed before being stable than, TF 2.11 support will probably be out with the next release.

**Comment by deepquantum88** [comment]
any hope when it will be released?

**Comment by jaeyoo** [comment]
https://github.com/tensorflow/quantum/issues/762#issuecomment-1509371564

Please, please rebuild TF 2.11.0 with the right build options: ABI is set to 1, std c++ is 17.

Here is the newly updated installation guideline:

https://github.com/tensorflow/quantum/blob/master/docs/install.md#4-build-tensorflow-from-source

**Comment by mhucka** [comment]
This issue appears related to older releases of TFQ and TF. Given the most recent comments, it appears likely that this has been resolved one way or another. In the interest of prioritizing work on TensorFlow Quantum, I will close this issue. Please reopen this issue if the original problem was not addressed.
