### ISSUE TITLE
can't impelement tensorflow federated, tensorflow and tensorflow_quantum 

### ISSUE THREAD

**Issue by Rayhan740** [tensorflow/quantum#760]
I wanted to verify a paper so I needed to apply tensorflow, tensorflow-quantum and tensorflow-federated at the same time or in a same environment and I tried different version but there is not compatible version that exist !🥲 .... I tried tensorflow==2.3.1 and tensorflow_quantum == 0.4.0 and tensorflow-federated==0.17.0 manually but the problem is it's still not compatible with each other.
Is there any solution for that?

**Comment by lockwo** [comment]
I don't see any matching versions of TFQ requirements on TF and TFF requirements. However, it is a little surprising they don't work since their requirements are only off by 0.0.1.

**Comment by Rayhan740** [comment]
yes there is no version but can tensorflow fix this problem?

**Comment by lockwo** [comment]
TFQ main and TFF 0.41.0 both have 2.11.0 requirements. But I'm not sure if the latest changes in TFQ are stable yet, so enter at your own risk (see https://github.com/tensorflow/quantum/issues/757)

**Comment by Rayhan740** [comment]
It doesn't work. is there any way to fix this problem?

**Comment by lockwo** [comment]
I'm not sure if any easy way, it you isolate the breaking points (which are probably minor since the versions are off by just 0.0.1) in TFF you could changed those and build from source, but I don't know anything about TFF so I can't comment much on it

**Comment by Rayhan740** [comment]
is there any way that I can get help ?? or can do something about it??

**Comment by jaeyoo** [comment]
I am bumping up the TFQ version to be compatible with v2.11.0 during this unstable phase, could you please share the installation error log that I can help you with?

Firstly, please see https://github.com/tensorflow/quantum/issues/764

**Comment by Rayhan740** [comment]
I guess there is a numpy file which is making all the fuss for tfq and tff ..... Is this solved yet?

**Comment by mhucka** [comment]
@Rayhan740 This issue has not been addressed for a long time. Did you eventually resolve it? Can this issue report be closed?

**Comment by Rayhan740** [comment]
id didn't get resolved. I stopped working on the topic after that.
