### ISSUE TITLE
Not working on Google Collab. Not able to install tensorflow quantum.

### ISSUE THREAD

**Issue by inojneupane** [tensorflow/quantum#794]
Error: Could not find a version that satisfies the requirement.

**Comment by lockwo** [comment]
https://github.com/tensorflow/quantum/issues/782, https://github.com/tensorflow/quantum/issues/791, https://github.com/tensorflow/quantum/issues/787, https://github.com/tensorflow/quantum/issues/768

**Comment by mhucka** [comment]
In the interest of prioritizing work on TensorFlow Quantum, I will close this issue as a duplicate of other issues. Please reopen this issue if that's incorrect.
