### ISSUE TITLE
NotFoundError: ...\core\ops\_tfq_simulate_ops.so not found

### ISSUE THREAD

**Issue by CalciferLWS** [tensorflow/quantum#800]
when I trying to do import tensorflow_quantum as tfq

I got error like this :

NotFoundError: NotFoundError: D:\download\anaconda\envs\tensorflowq\Lib\site-packages\tensorflow_quantum\core\ops\_tfq_simulate_ops.so not found

Package lists: python = 3.7.0    tensorflow = 2.2.0    tensorflow-quantum = 0.3.1    cirq = 0.8.0

What should I do?

**Comment by lockwo** [comment]
tfq 0.3.1 has requirements tensorflow==2.1.0 based on the requirements txt

**Comment by CalciferLWS** [comment]
your suggested solution worked, thank you very much!

> tfq 0.3.1 has requirements tensorflow==2.1.0 based on the requirements txt
