### ISSUE TITLE
CI formatter uses old clang-format version

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#87]
My local format check does not catch any problems, though the CI fails #72 .  It seems the "Install Format tools" section of the lint-and-format job installs `clang-format-3.8`, which is not available through standard apt-get.  Is there a way to keep required dev tool versions and CI versions in sync?

**Comment by MichaelBroughton** [comment]
This has gone stale. We currently use clang-format6 which should let people standardize to that. Closing for now can re-open if things come up.
